#:schema node_modules/wrangler/config-schema.json
name = "rfp-generator"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"                # Environment variable name
database_name = "local-db"    # Database name
database_id = "local"         # ID for local development
